eureka:
  client:
    service-url:
      defaultZone: http://root:root@euk1.com:7001/eureka/
  instance:
    metadata-map:
      dalao: consumer-02
spring:
  application:
    name: user-consumer
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      rate: 1
  boot:
    admin:
      client:
        url: http://localhost:7020
server:
  port: 7008
feign:
  circuitbreaker:
    enabled: true

hystrix:
  dashboard:
    proxy-stream-allow-list: "localhost"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
